CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(1024) NOT NULL,
    OAUTH_ID VARCHAR(1024),
    AVATAR_URL VARCHAR(1024),
    "LOCATION" VARCHAR(1024)
);

CREATE TABLE USER_SESSIONS (
    ID SERIAL PRIMARY KEY,
    SESSION_ID VARCHAR(1024) UNIQUE NOT NULL,
    USER_ID INT NOT NULL REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    SESSION_DATA JSONB NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EXERCISES (
    ID SERIAL PRIMARY KEY,
    EXERCISE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE SYMPTOMS (
    SYMPTOM_ID SERIAL PRIMARY KEY,
    SYMPTOM_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE JOURNAL_ENTRIES (
    JOURNAL_ENTRY_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL REFERENCES USERS ON DELETE CASCADE,
    SYMPTOM_ID INT NOT NULL REFERENCES SYMPTOMS ON DELETE CASCADE,
    EXERCISE_ID INT NOT NULL REFERENCES EXERCISES ON DELETE CASCADE,
    JOURNALS_ID INT NOT NULL REFERENCES JOURNALS ON DELETE CASCADE,
    JOURNAL_ENTRY_DATE DATE NOT NULL
);

CREATE TABLE JOURNALS (
    JOURNALS_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL REFERENCES USERS ON DELETE CASCADE,
    JOURNAL_NAME VARCHAR(100) NOT NULL
);
