CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(1024) NOT NULL,
    USER_PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE EXERCISES (
    ID SERIAL PRIMARY KEY,
    EXERCISE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE SYMPTOMS (
    SYMPTOM_ID SERIAL PRIMARY KEY,
    SYMPTOM_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE JOURNAL_ENTRIES (
    JOURNAL_ENTRY_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL REFERENCES USERS ON DELETE CASCADE,
    SYMPTOM_ID INT NOT NULL REFERENCES SYMPTOMS ON DELETE CASCADE,
    EXERCISE_ID INT NOT NULL REFERENCES EXERCISES ON DELETE CASCADE,
    JOURNALS_ID INT NOT NULL REFERENCES JOURNALS ON DELETE CASCADE,
    JOURNAL_ENTRY_DATE DATE NOT NULL
);

CREATE TABLE JOURNALS (
    JOURNALS_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL REFERENCES USERS ON DELETE CASCADE,
    JOURNAL_NAME VARCHAR(100) NOT NULL
);
